import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Poppins } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/navbar/Navbar'
import Footer from '@/components/footer/Footer'

const poppins = Poppins({ subsets: ['latin'], weight: ['100', '200', '300', '400', '500', '600', '700', '800'] })

export const metadata: Metadata = {
  title: 'Fullstack NextJs Typescript',
  description: 'Generated by NextJS 14.0.3',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className="container bg-purple-800">
          <Navbar/>
          {children}
          <Footer/>
        </div>
      </body>
    </html>
  )
}
